language: java
jdk:
- oraclejdk8
- openjdk8
dist: trusty
script: mvn clean install site
env:
  matrix:
    secure: AVFhPadriChDFAi6WzcifaEmjXaIdNCMmmsCr2CJw63SptFZ9HcC670oJWTGxVvWCGjTOQAXkwcD1ND4poJCfuXbaN/STPSQxAfF6KGrtMwVcssfbQU0h2XG2N/I8VNcldBFsCwGIe+tvUCnVK0bH9Clst/3sC5HokI4CPGL5YUG+c57rkhh4PDl5gsJHbBdbO7XL8ftjnBkWPuZ9s6NnzJEe12G8s4llUGyzPUpYVer+L0iREdCgAbvD1HZ7ejox2wEmDScKR58fnyF64m4MVOb5Wf0WCh3C9kZH1UrqqOl/ssG+sM6RuNf9piCizPfQWJ3tSiAaqWSO6DdHXS66MPipkeWg6fcqijz+yDgJbjqsB/0cV+oP3RFNbTHpG6oiFwMY4dX9Wnrz8wbhOiebWo2EwusUuV3JigvGrQQv0zxYkTauDDXCMEJGALDoU/QUNYtiQekx7AsNlUScNdqbL1+IZkcVQ8UdXUiZR8mTebpEFCpR5v1LShehq4G4jgp0d3x4KPnBbMjY00R5dmGOdAPRkzoCl7WHPg33VVWcFyyAJ6gn4ijPRvSofdEoffuI88MGFmtkgA/gzYEYkVAdKhmr+9URSwfhXFnNAXi3s9FLf7oi8RvwR7Bl85pOzTD5nzV6KxeVWI08pDq6PoORUc+QJjwulIdGSQNQg4nHbc=
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/site
  github_token: $GITHUB_TOKEN
  on:
    branch: master
